const sampleListings = [
  {
    title: "Seaside Surf Shack",
    description: "Catch the waves and enjoy laid-back vibes at this colorful surf shack steps from the Pacific.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a0b39?auto=format&fit=crop&w=800&q=60",
    price: 950,
    location: "Santa Cruz",
    country: "United States",
  },
  {
    title: "Minimalist Urban Flat",
    description: "Live smart in this sustainable minimalist flat, close to the metro and city hotspots.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&q=60",
    price: 1300,
    location: "Stockholm",
    country: "Sweden",
  },
  {
    title: "Chic Rooftop Penthouse",
    description: "Unwind in a sun-soaked penthouse with a rooftop terrace and panoramic city views.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 3400,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Classic Victorian Townhouse",
    description: "Stay in a lovingly restored Victorian home, minutes from museums and parks.",
    image: "https://images.unsplash.com/photo-1460474647541-4edd0cd0c746?auto=format&fit=crop&w=800&q=60",
    price: 1550,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Sunset Ridge Villa",
    description: "Enjoy spectacular sunsets and mountain views from this elegant hillside villa.",
    image: "https://images.unsplash.com/photo-1460492249730-251280d7b36b?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Cape Town",
    country: "South Africa",
  },
  {
    title: "Beachside Bamboo Bungalow",
    description: "Relax in this eco-conscious, bamboo-built bungalow just steps from soft white sands.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 1050,
    location: "Goa",
    country: "India",
  },
  {
    title: "Downtown Designers Loft",
    description: "A stunning open-space loft for creative minds, featuring original artwork and modern furnishings.",
    image: "https://images.unsplash.com/photo-1519974719765-e6559eac2575?auto=format&fit=crop&w=800&q=60",
    price: 1850,
    location: "Chicago",
    country: "United States",
  },
  {
    title: "Eco Glamping Pod",
    description: "Experience the outdoors in comfort with this stylish and eco-friendly glamping pod.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?auto=format&fit=crop&w=800&q=60",
    price: 650,
    location: "Rotorua",
    country: "New Zealand",
  },
  {
    title: "Garden Cottage on Vineyard Estate",
    description: "Sip local wine and stroll among the vines in this romantic cottage on a sprawling vineyard.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    price: 1450,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Zen Mountain Retreat",
    description: "Rejuvenate your senses at this peaceful retreat with mountain views and private meditation decks.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Hokkaido",
    country: "Japan",
  },
  {
    title: "Lakeside Modern Cabin",
    description: "Stay cozy by the fireplace in this modern lakeside cabin close to hiking and fishing.",
    image: "https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Vancouver",
    country: "Canada",
  },
  {
    title: "Bohemian City Hideaway",
    description: "Find inspiration in this unique, artistic flat packed with music, books, and color.",
    image: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Lisbon",
    country: "Portugal",
  },
  {
    title: "Ski Cabin with Fireplace",
    description: "Warm up after a day on the slopes in this cozy ski cabin with stunning snow-capped views.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=60",
    price: 1750,
    location: "Chamonix",
    country: "France",
  },
  {
    title: "Sunlit Jungle Treehouse",
    description: "Immerse yourself in nature in this airy treehouse, high in the jungle canopy with sunlit decks.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Historic Townhouse in Old Quebec",
    description: "Step back in time in this lovingly preserved townhouse with cobbled street views.",
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=60",
    price: 1380,
    location: "Quebec City",
    country: "Canada",
  },
];

module.exports = { data: sampleListings };
